Task 1: NumPy Introduction & Arrays 

Create a Python program using NumPy that:

Imports NumPy.
Creates a NumPy array containing at least 10 numbers.

Displays the array.
Displays the array's shape, size, and data type.

Creates a one-dimensional and two-dimensional array.

In [2]:
import numpy as np
arr = np.array([10,20,30,40,50,60,70,80,90,100]) #1d array
arr2 = np.array([[10,20,30],[40,50,60],[70,80,90],[100,110,120]])
print(f"Array's shape: {arr.shape},\nArray's Size: {arr.size},\nArray's Datatype: {arr.dtype}")
print(f"Array's shape: {arr2.shape},\nArray's Size: {arr2.size},\nArray's Datatype: {arr2.dtype}")
print(f"one dimentional array:\n{arr}\nTwo dimentional array:\n{arr2}")


Array's shape: (10,),
Array's Size: 10,
Array's Datatype: int32
Array's shape: (4, 3),
Array's Size: 12,
Array's Datatype: int32
one dimentional array:
[ 10  20  30  40  50  60  70  80  90 100]
Two dimentional array:
[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]


Task 2: NumPy Indexing, Slicing & Reshaping 

Using a NumPy array:

Access specific elements using indexing.

Extract a portion of the array using slicing.

Create a two-dimensional array.

Access specific rows and columns.

Reshape an array into different dimensions.

Display the original and reshaped arrays.

In [3]:
import numpy as np
arr = np.array([10,20,30,40,50,60,70,80,90,100])
print(f'original array: {arr}')
print(f'Element accesing\n1st element: {arr[0]}\n2nd element:{arr[1]}\nNgative indexing\nlast element: {arr[-1]}')
print('Slicing of array')
print(arr[0:5])
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(f'original array:\n{arr2}')
print(f"2nd row of array:\n {arr2[1]}")
print(f'3rd column of array:\n {arr2[:,2]}')
print(f'Reshaping array:\n{arr2.reshape(3,4)}')
print(f'Reshaping array:\n{arr2.reshape(2,6)}')
print(f"original array:\n{arr2}\nReshaped array:\n{arr2.reshape(2,6)}")

original array: [ 10  20  30  40  50  60  70  80  90 100]
Element accesing
1st element: 10
2nd element:20
Ngative indexing
last element: 100
Slicing of array
[10 20 30 40 50]
original array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2nd row of array:
 [4 5 6]
3rd column of array:
 [ 3  6  9 12]
Reshaping array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaping array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
original array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Reshaped array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


Task 3: NumPy Mathematical & Statistical Operations (10 Marks)

Perform the following operations using NumPy:

Mathematical Operations
Addition
Subtraction
Multiplication
Division
Statistical Functions
Mean
Median
Minimum
Maximum
Standard Deviation
Sum

Use a numerical dataset of your choice and display the results.

In [4]:
import numpy as np
arr = np.array([10,20,30,40,50,60,70,80,110])
print(f'Original array:\n{arr}')
print(f'Addition operation:\n{arr+5}')
print(f'Substraction operation:\n{arr-5}')
print(f'multiplication operation:\n{arr*5}')
print(f'division operation:\n{arr/5}')
print(f'mean:\n{np.mean(arr)}')
print(f'median:\n{np.median(arr)}')
print(f'minimum:\n{np.min(arr)}')
print(f'maximum:\n{np.max(arr)}')
print(f'Standard Deviation:\n{np.std(arr)}')
print(f'Sum:\n{np.sum(arr)}')




Original array:
[ 10  20  30  40  50  60  70  80 110]
Addition operation:
[ 15  25  35  45  55  65  75  85 115]
Substraction operation:
[  5  15  25  35  45  55  65  75 105]
multiplication operation:
[ 50 100 150 200 250 300 350 400 550]
division operation:
[ 2.  4.  6.  8. 10. 12. 14. 16. 22.]
mean:
52.22222222222222
median:
50.0
minimum:
10
maximum:
110
Standard Deviation:
29.731307022799225
Sum:
470


Task 4: Pandas Series & DataFrame 

Create a Pandas program that:

Creates a Pandas Series.
Creates a DataFrame containing student or employee information.
Displays the DataFrame.
Displays the column names.
Displays the index.
Adds a new column to the DataFrame.
Displays the updated DataFrame.

In [5]:
import pandas as pd
data = pd.Series([1,2,3,4])
employee_info = pd.DataFrame({'Employee_name':['nachiket','akash','abhishek'],'Employee_id':[91,95,92],'email_id':['nachiket@gmail.com','ak@gmail.com','abhi@gmail.com']})
print(f'pandas series:\n{data}')
print(f'pandas dataframe:\n{employee_info}')
print(f'columns available:\n{employee_info.columns}')
print(f'indexies\n{employee_info.index}')
print('Adding employee_address in employee_info')
employee_info['Employee_address'] = ['kalaburgi','aland','kalaburgi']
print(f'updated datafram\n{employee_info}')


pandas series:
0    1
1    2
2    3
3    4
dtype: int64
pandas dataframe:
  Employee_name  Employee_id            email_id
0      nachiket           91  nachiket@gmail.com
1         akash           95        ak@gmail.com
2      abhishek           92      abhi@gmail.com
columns available:
Index(['Employee_name', 'Employee_id', 'email_id'], dtype='object')
indexies
RangeIndex(start=0, stop=3, step=1)
Adding employee_address in employee_info
updated datafram
  Employee_name  Employee_id            email_id Employee_address
0      nachiket           91  nachiket@gmail.com        kalaburgi
1         akash           95        ak@gmail.com            aland
2      abhishek           92      abhi@gmail.com        kalaburgi


Task 5: Reading & Inspecting Data 

Use a CSV dataset and perform the following operations:

Read the CSV file using Pandas.
Display the first 5 rows using head().
Display the last 5 rows using tail().
Check the number of rows and columns.
Display column names.
Check data types using dtypes.
Use info() and describe() to understand the dataset.

In [13]:
import seaborn as sns
import pandas as pd
df = sns.load_dataset('tips') #if we have file then pd.read_csv(file_path)
print(f'first 5 rows\n{df.head()}')
print(f'last 5 rows\n{df.tail()}')
print(f'number of rows and columns are: (row,col) = {df.shape}')
print(f'Columns available:\n{df.columns}')
print(f'datatype\n{df.dtypes}')
print(df.info())
print(df.describe())

first 5 rows
   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
last 5 rows
     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2
number of rows and columns are: (row,col) = (244, 7)
Columns available:
Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')
datatype
total_bill     float64
tip            float64
sex           category
smoker        category
day           category
time          category
size 

Task 6: Selecting, Filtering & Sorting Data

Using a Pandas DataFrame:

Select specific columns.
Select specific rows.
Filter records based on a condition.
Apply multiple filtering conditions.
Sort data in ascending order.
Sort data in descending order.

Example: Filter students based on marks, employees based on salary, or products based on price.

In [23]:
import seaborn as sns
import pandas as pd
df = sns.load_dataset('titanic')
print(df.head(3)) #to know the dataset
print(f'selecting columns\n{df['class']}')
print(f'selecting a row:\n{df.iloc[0:2]}')
print(f'selecting males only')
print(df[df['sex']=='male'])
print(df.sort_values(by='fare', ascending=True))
print(df.sort_values(by='fare',ascending=False))

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
selecting columns
0       Third
1       First
2       Third
3       First
4       Third
        ...  
886    Second
887     First
888     Third
889     First
890     Third
Name: class, Length: 891, dtype: category
Categories (3, object): ['First', 'Second', 'Third']
selecting a row:
   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1   

Task 7: Handling Missing Values 

Take a dataset containing missing values and perform the following:

Identify missing values using isnull() / isna().
Count missing values in each column.
Remove rows containing missing values.
Fill missing values using appropriate methods.
Display the dataset before and after handling missing values.

Briefly explain why handling missing data is important in Data Analytics

In [51]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Rahul", "Priya", "Amit", "Sneha", "Karan", "Neha"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", None],
    "Age": [25, 28, np.nan, 30, 27, 26],
    "Salary": [50000, 45000, 60000, np.nan, 48000, 70000],
    "Experience": [2, 4, 3, 5, np.nan, 4]
}

df = pd.DataFrame(data)
df_original = df
print(f'identifing missing values:\n{df.isnull}')
print(f'classifying missing values:\n{df.isnull().sum()}')
print(f'removing rows contains missing values:\n{df.dropna(inplace=False)}')#for permanent change use inplace=True
print(f'filling missing values:')
print(f'filling Age with mean\n{df['Age'].fillna(df["Age"].mean(),inplace=True)}')
print(f'filling salary with mean\n{df['Salary'].fillna(df['Salary'].mean(),inplace=True)}')
print(f'filling Experience with median\n{df['Experience'].fillna(df['Experience'].median(),inplace=True)}')
print(f'filling department using na:\n{df['Department'].fillna('Na',inplace=True)}')
print(f'original dataset:\n{df_original}')
print(f'updated dataset:\n{df}')



identifing missing values:
<bound method DataFrame.isnull of     Name Department   Age   Salary  Experience
0  Rahul         IT  25.0  50000.0         2.0
1  Priya         HR  28.0  45000.0         4.0
2   Amit         IT   NaN  60000.0         3.0
3  Sneha    Finance  30.0      NaN         5.0
4  Karan         HR  27.0  48000.0         NaN
5   Neha       None  26.0  70000.0         4.0>
classifying missing values:
Name          0
Department    1
Age           1
Salary        1
Experience    1
dtype: int64
removing rows contains missing values:
    Name Department   Age   Salary  Experience
0  Rahul         IT  25.0  50000.0         2.0
1  Priya         HR  28.0  45000.0         4.0
filling missing values:
filling Age with mean
None
filling salary with mean
None
filling Experience with median
None
filling department using na:
None
original dataset:
    Name Department   Age   Salary  Experience
0  Rahul         IT  25.0  50000.0         2.0
1  Priya         HR  28.0  45000.0         4.

C:\Users\nachi\AppData\Local\Temp\ipykernel_14960\105870874.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  print(f'filling Age with mean\n{df['Age'].fillna(df["Age"].mean(),inplace=True)}')
C:\Users\nachi\AppData\Local\Temp\ipykernel_14960\105870874.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values 

Task 8: Merge, Concatenate, GroupBy & Pivot Table 

Using two or more datasets, perform the following operations:

Merge & Concatenate
Merge two DataFrames using a common column.
Concatenate two DataFrames.
GroupBy
Group data based on a selected column.
Calculate aggregate values such as sum, mean, count, minimum, or maximum.
Pivot Table
Create a Pivot Table using Pandas.
Summarize the data based on appropriate rows, columns, and values.

In [52]:

import pandas as pd

employees = pd.DataFrame({
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Rahul", "Priya", "Amit", "Sneha", "Karan"],
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000]
})

locations = pd.DataFrame({
    "Employee_ID": [101, 102, 103, 104, 105],
    "City": ["Bangalore", "Mumbai", "Bangalore", "Pune", "Mumbai"],
    "Experience": [2, 4, 3, 5, 2]
})
merged_df = pd.merge(
    employees,
    locations,
    on="Employee_ID",
    how="inner"
)

print("Merged DataFrame:")
print(merged_df)
new_employees = pd.DataFrame({
    "Employee_ID": [106, 107],
    "Name": ["Neha", "Arjun"],
    "Department": ["IT", "Finance"],
    "Salary": [70000, 52000]
})

concatenated_df = pd.concat(
    [employees, new_employees],
    ignore_index=True
)

print("\nConcatenated DataFrame:")
print(concatenated_df)


grouped = employees.groupby("Department")["Salary"].sum()

print("\nTotal Salary by Department:")
print(grouped)


grouped_stats = employees.groupby("Department")["Salary"].agg(
    ["sum", "mean", "count", "min", "max"]
)

print("\nSalary Statistics by Department:")
print(grouped_stats)

pivot = pd.pivot_table(
    merged_df,
    values="Salary",
    index="Department",
    columns="City",
    aggfunc="mean"
)

print("\nPivot Table:")
print(pivot)

Merged DataFrame:
   Employee_ID   Name Department  Salary       City  Experience
0          101  Rahul         IT   50000  Bangalore           2
1          102  Priya         HR   45000     Mumbai           4
2          103   Amit         IT   60000  Bangalore           3
3          104  Sneha    Finance   55000       Pune           5
4          105  Karan         HR   48000     Mumbai           2

Concatenated DataFrame:
   Employee_ID   Name Department  Salary
0          101  Rahul         IT   50000
1          102  Priya         HR   45000
2          103   Amit         IT   60000
3          104  Sneha    Finance   55000
4          105  Karan         HR   48000
5          106   Neha         IT   70000
6          107  Arjun    Finance   52000

Total Salary by Department:
Department
Finance     55000
HR          93000
IT         110000
Name: Salary, dtype: int64

Salary Statistics by Department:
               sum     mean  count    min    max
Department                               

Task 9: Exporting Data 
After processing the dataset:

Export the final DataFrame to a new CSV file.
Verify that the exported file contains the processed data.
Save the file properly for submission.

In [53]:
import pandas as pd
df = pd.DataFrame({
    "Name": ["Rahul", "Priya", "Amit", "Sneha", "Karan"],
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [50000, 45000, 60000, 55000, 48000]
})
file_name = "cleaned_employees.csv"

df.to_csv(file_name, index=False)
print("Data exported successfully to:", file_name)
exported_df = pd.read_csv(file_name)
print("\nData from Exported CSV File:")
print(exported_df)

Data exported successfully to: cleaned_employees.csv

Data from Exported CSV File:
    Name Department  Salary
0  Rahul         IT   50000
1  Priya         HR   45000
2   Amit         IT   60000
3  Sneha    Finance   55000
4  Karan         HR   48000
